variables:
  NAME: interkonekto
  PACKAGE_PATH: /go/src/gitlab.com/hall/$NAME

build:
  stage: build
  image: golang:1.11
  before_script:
    - mkdir -p $(dirname $PACKAGE_PATH)
    - cp -r $CI_PROJECT_DIR $PACKAGE_PATH
    - cd $PACKAGE_PATH
  script:
    - go get ...
    - go build
  after_script:
    - mv $PACKAGE_PATH/$NAME $CI_PROJECT_DIR/
  artifacts:
    paths:
      - $NAME

deploy:
  stage: deploy
  image: google/cloud-sdk
  stage: deploy
  environment: production
  only:
    - master
  before_script:
    - echo $DEPLOY_KEY_FILE_PRODUCTION > /tmp/$CI_PIPELINE_ID.json
    - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
    - rm /tmp/$CI_PIPELINE_ID.json
  script:
    - gcloud --quiet --project $CI_PROJECT_NAME app deploy
