build:
  stage: build
  image: golang:1.11
  script:
  - go get ...
  - go build
  artifacts:
    paths:
      - $CI_PROJECT_NAME

deploy:
  stage: deploy
  image: google/cloud-sdk
  stage: deploy
  environment: production
  only:
    - master
  before_script:
    - echo $DEPLOY_KEY_FILE_PRODUCTION > /tmp/$CI_PIPELINE_ID.json
    - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
    - rm /tmp/$CI_PIPELINE_ID.json
  script:
    - gcloud --quiet --project $PROJECT_ID_PRODUCTION app deploy
