= interkonekto
:uri: https://api.linguo.io

The API at {uri} returns (in the JSON format) data of words in the Ido language.


== format

Requests are constructed in the following manner:

{uri}/__query__/__data__


=== query

Preceeding the query with an ISO language code, followed by a colon, will treat the query and being written in that language.

WARNING: this feature is not currently available.

If the query is preceeded by a tilde, it is interpreted as a regular expression.

NOTE: the `%` and `#` characters in a URI are predefined; they'll mangle your regex.


=== data

The data options are:

 - semantiko
 - morfologio
 - exemplaro
 - sinonimo
 - kompundi
 - kategorio
 - an https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes[ISO language code]

NOTE: The special request {uri}/* will return a list of the available data options.

Multiple selections are made by delimiting options with a coma.
The lack of specifying data returns all data for matched queries.

== action

HTTP methods

 - GET: lektar //read

WARNING: the following are not yet implemented:

 - POST: krear //create
 - PUT: skribar //write / update
 - DELETE: efacar //delete


== examples

NOTE: these examples include extra formatting for legability

To return the definition of *linguo*, with example usage:

.GET {uri}/linguo/semantiko,exemplaro
[source,json]
----
{
  "linguo": {
    "exemplaro": [
      "matrala linguo"
      "intermixo di lingui",
    ],
    "semantiko": "Vortaro e sintaxo propra a komuneso."
  }
}
----

To return matches of the Russian word *язык*:

.GET {uri}/ru:язык
[source,json]
----
{
  "язык": {
    ...
    "io": "linguo",
    ...
    "ru": "язык",
    ...
  }
}
----

To return the English translation of every word that begins with *vort*:

.GET {uri}/~^vort.*/en
[source,json]
----
{
  "vortala": {
    "en": "verbal"
  },
  "vortifo": {
    "en": "word formation"
  },
  "vortope": {
    "en": "literally, word for word"
  }
  ...
}
----

